name: R tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install testthat
        run: Rscript -e "install.packages('testthat', repos='https://cloud.r-project.org')"

      # If you have more deps, install them here (or switch to renv). 

      - name: Run tests
        run: Rscript -e "testthat::test_dir('tests')"

      # (Optional) Upload test logs/artifacts if you write them to files
      # - name: Upload test output
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-logs
      #     path: tests/testthat/*.Rout*
      #     if-no-files-found: ignore

